package com.wso2telco.services.dep.sandbox.util;

public enum ProvisioningStatusCodes {
	
	PRV_PROVISION_SUCCESS, PRV_PROVISION_FAILED, PRV_PROVISION_PENDING, PRV_PROVISION_ALREADY_ACTIVE, PRV_DELETE_SUCCESS, PRV_DELETE_FAILED, PRV_DELETE_PENDING, PRV_DELETE_NOT_ACTIVE

}
