package com.wso2telco.services.dep.sandbox.util;

public enum RequestType {
    SMSMESSAGING, PAYMENT, USSD, LOCATION, MOBILEID, PROVISIONING,PROVISIONINGCONFIG, USER, CUSTOMERINFO,CUSTOMERINFOCONFIG, CREDIT,  WALLET, WALLETCONFIG, USSDCONFIG, SMSCONFIG;

}
